spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.16.146:3306/demo?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jooq:
    sql-dialect: mysql
  data:
    mongodb:
      database: test
      username: test
      password: test
      host: 116.62.16.146
      authentication-database: admin
      port: 27017
