spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.16.146:3306/seata?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jooq:
    sql-dialect: mysql
  data:
    mongodb:
      database: test
      uri: mongodb://116.62.62.146:27017