server:
  port: 8001
spring:
  application:
    name: galaxy-business-common
  profiles:
    include: common
  mail:
    host: mail.btsea.com
    username: btsea01@btsea.com
    port: 25
    protocol: smtp
    default-encoding: UTF-8
  data:
    mongodb:
      host: 192.168.21.30
      port: 27011
      username: root
      password: rootpasswd
      database: test1
      authentication-database: admin
  swagger:
    basePackage: com.cloud.galaxy
    license:
      name: galaxy
  kafka:
    bootstrap-servers: 192.168.21.25:9092,192.168.21.29:9092,192.168.21.30:9092
    consumer:
      group-id: kafka2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
      bootstrap-servers: 192.168.21.25:9092,192.168.21.29:9092,192.168.21.30:9092
sms:
  urls: https://BJJS009518:cd2019@sdk2.028lk.com/sdk2/BatchSend2.aspx,https://BJJS009517:cd2019@sdk2.028lk.com/sdk2/BatchSend2.aspx
  international:
    url: https://BJJS009571:cd2019@sdk2.028lk.com/sdk2/BatchSend2.aspx,https://BJJS009570:cd2019@sdk2.028lk.com/sdk2/BatchSend2.aspx
  hour_max_send: 5
  day_max_send:  10
fdfs:
  tracker-list: 192.168.21.29:22122
  connect-timeout: 60
  so-timeout: 60
  thumb-image:
    width: 150
    height: 150
img:
   width: 50
   height: 50
