server:
  port: 8001
spring:
  application:
    name: galaxy-business-file
  profiles:
    include: common
  data:
    mongodb:
      host: 116.62.16.146
      port: 27017
      username: test
      password: test
      database: test
      authentication-database: admin
fdfs:
  tracker-list: 192.168.21.29:22122
  search-list: 192.168.21.29:80
  connect-timeout: 60
  so-timeout: 60
  thumb-image:
    width: 1
    height: 1
